### ISSUE TITLE
killed during inference

### ISSUE THREAD

**Issue by lonestar234028** [amazon-science/mm-cot#41]
Hi Expert, can you give me some guidance? 
I have tuned some parameters, but still can not work..

Code:
```

CUDA_VISIBLE_DEVICES=0 python main.py \
    --model allenai/unifiedqa-t5-base \
    --user_msg rationale --img_type detr \
    --bs 1 --eval_bs 1 --eval_acc 5 --output_len 256 \
    --final_eval --prompt_format QCM-LE \
    --evaluate_dir models/MM-CoT-UnifiedQA-base-Rationale
```
MY env:

![image](https://user-images.githubusercontent.com/11569402/225975241-69d52b7c-c31c-4ef8-ae33-4aa8b4fac191.png)

ERROR:

![image](https://user-images.githubusercontent.com/11569402/225975342-5bbf025e-659d-4c3a-b173-f2b11a772577.png)

**Comment by lonestar234028** [comment]
Hi expert I have fixed this issue by adding 3 other GPUs.

**Comment by WeixuanXiong** [comment]
Thanks for sharing. I'm wondering if you just let `CUDA_VISIBLE_DEVICES=0` becomes `CUDA_VISIBLE_DEVICES=0,1,2,3` to solve this problem?

**Comment by lonestar234028** [comment]
@WeixuanXiong  Yes, I have added another GPU, which means CUDA_VISIBLE_DEVICES=0,1
