### ISSUE TITLE
Question about vision feature extractor

### ISSUE THREAD

**Issue by YihanCao123** [amazon-science/mm-cot#49]
Hi authors, first of all, thanks for your amazing work on scienceqa dataset!

I have a question concerning the image processing details in your work. I'm not very familiar with computer vision, so I'm a bit confused about how you processed these images. Did you use CLIPFeatureExtractor, or DetrFeatureExtractor, or just used the last hidden state of DetrModel? And could you share the image processing code if possible?

Thanks!

**Comment by gianfrancodemarco** [comment]
They shared it here https://github.com/amazon-science/mm-cot/pull/45

**Comment by cooelf** [comment]
Yes. Please check the latest code.
