### ISSUE TITLE
Why can't I generate the correct rationales when I don't give the solution label to the validation set or test set?

### ISSUE THREAD

**Issue by zhongfansun** [amazon-science/mm-cot#78]
Why can't I generate the correct rationales when I don't give the solution label to the validation set or test set? the generated rationales are as follows:
![4c1365618719a0cf846cfaf3b4aaecc](https://github.com/user-attachments/assets/b51bc03b-7ac5-485c-8e39-b46f550de674)
Looking forward to your reply.

**Comment by WRJ3431** [comment]
Have you found a solution?
